// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3mvqRpQa-KVoFR96kkV6uJ-QFb1GG5TU',
    appId: '1:786466697836:web:86ffe519f1b0233feede49',
    messagingSenderId: '786466697836',
    projectId: 'visitants-cond',
    authDomain: 'visitants-cond.firebaseapp.com',
    storageBucket: 'visitants-cond.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvhIppIq4aVuiM2Lren5B-de1fjLY7ac',
    appId: '1:786466697836:android:9210d8c433a90e47eede49',
    messagingSenderId: '786466697836',
    projectId: 'visitants-cond',
    storageBucket: 'visitants-cond.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0LE2f_S85HoIa0g37J1w40zNfiC4ylQI',
    appId: '1:786466697836:ios:e07d862dfba8bd91eede49',
    messagingSenderId: '786466697836',
    projectId: 'visitants-cond',
    storageBucket: 'visitants-cond.appspot.com',
    iosClientId: '786466697836-kjim7166q7s8lcsphael9jh1gfsfouj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitants',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0LE2f_S85HoIa0g37J1w40zNfiC4ylQI',
    appId: '1:786466697836:ios:d4c3e782e7566b90eede49',
    messagingSenderId: '786466697836',
    projectId: 'visitants-cond',
    storageBucket: 'visitants-cond.appspot.com',
    iosClientId: '786466697836-ofdiq2g7k8gkn0runhc99gklei7dib1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.visitants.RunnerTests',
  );
}
